import React from 'react'
import './Statistics.css';
import { Row, Col } from 'antd';
import Header from '../../header/Header'
// import ClimateObjective from './ClimateObjective'
import PanelsHeatMap from './PanelsHeatMap';
import axiosConfig from '../../api/axiosConfig'


var position = { lat: 39.8714243295929, lng: -0.06466403603553773 }
// var totalInstallations, totalPower;

class Statistics extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      totalInstallations: '',
      totalPower: ''
    };
  }

  getAllInstallationsNumber() {
    axiosConfig({
      url: '/solarPanel/gettotalnumber',
      method: 'GET'
    }).then(response => {
      this.setState({ totalInstallations: response.data });
      // console.log("TOTAL INSTALLATIONS NUMBER", totalInstallations)
    });
  }

  getAllInstallationsPower() {
    axiosConfig({
      url: '/solarPanel/gettotalenergy',
      method: 'GET'
    }).then(response => {
      // totalPower = response.data;
      this.setState({ totalPower: response.data });
      // console.log("TOTAL INSTALLATION POWER", totalPower)
    });
  }


  componentDidMount() {
    this.getAllInstallationsNumber();
    this.getAllInstallationsPower();
  }

  render() {
    document.body.classList.remove('body_forms');
    return (
      <React.Fragment >
        <Header />
        <Row>
          {/* <div id="background-statistics"> */}
          <Col xs={24} sm={12} md={12} lg={12} xl={12} >
            <div id="statistics-map-container" >
              <PanelsHeatMap />
            </div>
          </Col>
          <Col id="container-cards" xs={24} sm={12} md={12} lg={12} xl={12} >
            <Row >
              <div id="capacity-card-statistics-container" >
                <h2 id="tittle-installed">TOTAL SOLAR FACILITIES</h2>
                <h1 style={{ color: "#2a4092" }} id="numbers-installed">
                  {this.state.totalInstallations}
                </h1>
                {/* <p id="big-letters-installed"> MW</p> */}
                <p style={{ color: "#bfc5d2" }} id="small-letters-installed">
                  Total number of registered solar installations in the Greco project
                </p>
              </div>
            </Row>
          </Col>
          <Col id="container-cards" xs={24} sm={12} md={12} lg={12} xl={12} >
            <Row >
              <div id="climate-objective-card-statistics-container" >
                <h2 id="tittle-installed">TOTAL POWER</h2>
                <div id="cipher">
                  <h1 style={{ color: "#2a4092" }} id="numbers-climate-objective" >
                    {this.state.totalPower}
                  </h1>
                  <p id="letters-climate-objective">Kw</p>
                  <p style={{ color: "#bfc5d2" }} id="small-letters-installed">
                    Total Power generated by the sun and collected by the panels registered in the Greco project
                  </p>
                  {/* <p id="small-letters-climate">Target 2030</p> */}
                </div>
                {/* <ClimateObjective /> */}
              </div>
            </Row>
          </Col>
          {/* </div> */}
        </Row>
      </React.Fragment >
    );
  }
}

export default Statistics